<?php 
define('CNF_APPNAME','HR System');
define('CNF_APPDESC','HR System');
define('CNF_COMNAME','');
define('CNF_EMAIL','');
define('CNF_METAKEY','');
define('CNF_METADESC','');
define('CNF_GROUP','3');
define('CNF_ACTIVATION','confirmation');
define('CNF_MULTILANG','0');
define('CNF_LANG','');
define('CNF_REGIST','false');
define('CNF_FRONT','false');
define('CNF_RECAPTCHA','false');
define('CNF_THEME','sximone');
define('CNF_RECAPTCHAPUBLICKEY','');
define('CNF_RECAPTCHAPRIVATEKEY','');
define('CNF_MODE','development');
define('CNF_LOGO','backend-logo_1622544791.png');
define('CNF_ALLOWIP','');
define('CNF_RESTRICIP','192.116.134 , 194.111.606.21 ');
define('CNF_VACATION','');
define('CNF_START_HOUR','');
define('CNF_END_HOUR','');
define('CNF_TOLERANCE','');
define('VACATIONS_PER_YEAR','21');
define('PERMISSIONS_PER_MONTH','2');
define('PERMISSIONS_Hours_PER_MONTH','4');
define('CNF_BUILDER_TOOL','1');
define('delay_notifications_email','hr@ivas.com.eg');
?>